### ISSUE TITLE
Merge others work

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#100]
<a href="https://github.com/edillmann"><img src="https://avatars.githubusercontent.com/u/2512794?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [edillmann](https://github.com/edillmann)**
_Tue Feb  9 19:55:36 2016_
_Originally opened as https://github.com/mistifyio/go-zfs/pull/36_

---

I create this pull request to merge work done by apatil and calmh

[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mistifyio/go-zfs/36)

---

_**[edillmann](https://github.com/edillmann)** included the following code: https://github.com/mistifyio/go-zfs/pull/36/commits_

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Tue Feb  9 20:56:29 2016_

---

Hmm @edillmann I'll go ahead and merge @apatil's PR directly while taking care of the comments @trisk and I had. Also, unless he doesn't particularly want to and you need the functionality I'd rather @calmh submit the commits himself.

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Tue Feb  9 23:01:07 2016_

---

quick update: just ran into a failing test for `Diff` when testing #33  due to https://github.com/zfsonlinux/zfs/commit/141b6381d38a16a6178edcec8ace28d1f23b884e. Tests pass with a quick hack which needs correct handling.

**Comment by pjnorton** [comment]
<a href="https://github.com/calmh"><img src="https://avatars.githubusercontent.com/u/125426?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [calmh](https://github.com/calmh)**
_Thu Feb 11 09:45:48 2016_

---

(The zfs package is something I used for one thing but currently don't, so I don't have the drive to integrate my changes, whatever they were, at the moment. :)

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Thu Feb 11 15:37:13 2016_

---

@calmh thats fair.

@edillmann can you rebase on top of master, I've merged w/ tweaks @apatil's PR.

**Comment by pjnorton** [comment]
<a href="https://github.com/edillmann"><img src="https://avatars.githubusercontent.com/u/2512794?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [edillmann](https://github.com/edillmann)**
_Thu Feb 25 21:55:02 2016_

---

I repushed this PR, tests are OK

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Fri Mar 11 21:18:41 2016_

---

@edillmann breaking the API is a no-go. You're going to have to define other functions. I'd suggest something mimicking https://godoc.org/github.com/mistifyio/gozfs#Datasets, but unfortunately a different name :(

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/go-zfs/36#-:-KCbX7p5EGVhqSdr-Wgh:620680705)_

**Comment by joshie** [comment]
@mmlb did this request go dead?

**Comment by mmlb** [comment]
Seems that way, was an API breaking change so we can close.
