### ISSUE TITLE
Stop using overlay in favor of boottime /etc manipulation from config files

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#103]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Tue Mar 15 12:49:43 2016_
_Originally opened as https://github.com/mistifyio/mistify-os/issues/167_

---

@pjnorton commented on [Tue Mar 15 2016](https://github.com/mistifyio/mistify/issues/50)
# Description:

TBD

**Comment by joshie** [comment]
We have stopped using an overlay. I am closing this, as we already point to other places for certain config. Anything else will be opened as a more descriptive issue when needed.
