### ISSUE TITLE
Fix Image Name in Manifest for Docker v1.10.0 images

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#104]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Wed Mar  2 20:11:59 2016_
_Originally opened as https://github.com/mistifyio/mistify-agent-docker/issues/22_

---

Older exported docker images, such as those made by `docker 1.7.0`, contain several layer directories and a `repositories` file. That file is a short JSON object holding the repo name, tag, and hash.

``` javascript
{
    "tauzero/test-loop": {
        "latest": "a8967fd6aec812a6795ffe4953d416532b3866e168f60066a241d08ba700998e"
    }
}
```

When we import docker images from the image service, the `repositories` file is updated with the assigned uuid name using the `fixRepositoriesFile` function.

New exported images, such as those made by `docker 1.10.0` include an additonal file, the `manifest.json`

``` javascript
[{
    "Config": "8f898785cff843b9ab330ed35924c1d72bc7a37e66386232e3d95027f2b6659d.json",
    "RepoTags": ["tauzero/test-loop:latest"],
    "Layers": ["768d4f50f65f00831244703e57f64134771289e3de919a576441c9140e037ea2/layer.tar", "b3bbc4636fc59ec067f4a877899f2e008bf3e2fe55451ef78c090dd9709b3818/layer.tar", "1743d7c353b09160d6c8bc8f7cea2fcdbeaea2330d98f14ab723757ee5f16e38/layer.tar", "5634dce3a0081ec88be6e9dc149829a775b11b94bf2116f822a7bd688a99aaea/layer.tar", "92abfeb6712856ca6c60039d7eded949de973d2c8209516a68cee4ab7088f223/layer.tar", "ace0fd45046091a3b90d0d7f22aa6333ea350875532ee3ee95eb0cd74fe278eb/layer.tar"]
}]
```

Simply updating the `repositories` is no longer enough; I believe it is left in for backward compatibility. The `manifest.json` file will also need to be updated, specifically the `RepoTags` property, for this to work with the latest docker.

**Comment by pjnorton** [comment]
<a href="https://github.com/amoghe"><img src="https://avatars.githubusercontent.com/u/1750664?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [amoghe](https://github.com/amoghe)**
_Thu Mar 17 06:48:35 2016_

---

@TauZero could you point me to the official specification for this manifest file? I can't seem to find where this new file is documented.

**Comment by pjnorton** [comment]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TauZero](https://github.com/TauZero)**
_Thu Mar 17 14:15:49 2016_

---

I'll see if I can find it. I got the above information from exporting an image with older and newer versions of docker and checking the exported contents. Interesting that descriptions of a "manifest" that I can find so far don't follow the format that export gave me.

**Comment by joshie** [comment]
We don't use a docker agent anymore. Closing.
