### ISSUE TITLE
Viability of Eliminating SquashFS from NixOS

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#133]
## Issue Description

The desire is not to be reliant on SquashFS as part of NixOS.  Explore if this can be achieved and still allow us to use NixOS for cerana.
## Acceptance Criteria (How do we know when this is done?)

If we determine that we can use NixOS without SquashFS.  Latest date for making this determination will be end of current sprint on 4/22/2016.

**Comment by nshalman** [comment]
Can be done.

**Comment by nshalman** [comment]
https://github.com/NixOS/nixpkgs/commit/aacbf2b4808fceddc78b5edcbdfbe94d16968ff1 does work, though it's a bit hacky, but the point is that this can definitely be done.
