### ISSUE TITLE
Put ZFS into NixOS for Cerana

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#135]
## Issue Description

Assuming moving forward with NixOS ( #133), get ZFS implemented in NixOS.
## Acceptance Criteria (How do we know when this is done?)

ZFS is part of NixOS implementation within Cerana.
## Related Tickets
#133 (Dependency)

**Comment by bbickerton** [comment]
Additional Requirement:

For the `cerana/cerana/zfs` package, we rely on the https://github.com/ClusterHQ/zfs/tree/libzfs_core-HEAD fork of `zfs` containing a new stable ioctl API in combination with the upstream `spl`. From the cerana travis file:

```
V_ZFS=0.6.5.5
...
curl -L https://github.com/zfsonlinux/zfs/releases/download/zfs-$V_ZFS/spl-$V_ZFS.tar.gz | tar xz
git clone https://github.com/ClusterHQ/zfs -b libzfs_core-HEAD && (cd zfs && git checkout 2c9b2d6bf312d0ffb4a14c0570fcb8150196a9be)
MAKEFLAGS=-j$(($(grep -c '^processor' /proc/cpuinfo) * 2 + 1))
(cd spl-$V_ZFS && ./configure --prefix=/usr && make && sudo make install)
(cd zfs && ./autogen.sh && ./configure --prefix=/usr --with-spl=/usr/src/spl-$V_ZFS && make && sudo make install)
sudo modprobe zfs
```

Note that with spl 0.6.5.5, you need to specify the `--with-spl` flag when building the fork `zfs` as it expects a different versioned path.

**Comment by nshalman** [comment]
https://github.com/nshalman/nixpkgs/tree/cerana-test4 (specifically https://github.com/nshalman/nixpkgs/commit/e7efbb53675b645cf07a79a3df9c1a89de9bbb13) shows that this can be done.
