### ISSUE TITLE
Cerana Email

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#139]
## Issue Description

Establish emails for the Cerana team.
## Acceptance Criteria (How do we know when this is done?)

Emails are established for Cerana team members.
## Related Tickets
#138 - Cerana mailing list

**Comment by nshalman** [comment]
abuse@cerana.org is now wired up. I'm not convinced that any other individual email addresses are critical at this juncture.

**Comment by nshalman** [comment]
cerana.org email addresses can be easily created as needed. Currently being managed internally at OmniTI.
