### ISSUE TITLE
Build Docker Container on Dev4

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#164]
## Issue Description

Build Docker Container on Dev4

**Comment by StevenIsaacs** [comment]
Dev-4 runs Mistify-0S and Mistify-OS is not running an up to date version of Docker which supports the "ARG" keyword in Dockerfiles which is required to build the image. Because of this I abandoned the effort.

**Comment by StevenIsaacs** [comment]
This is no longer relevant since moving to NixOS.
