### ISSUE TITLE
Mock Cluster Config Provider

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#165]
## Issue Description

In order to complete adequate testing of #159 Status Pusher, several mock providers must be made.  The scope of this card is to create a mock cluster config provider.  The real provider is being handled in #145.
## Acceptance Criteria (How do we know when this is done?)

Functioning well enough to complete testing on #159.
## Related Tickets
#159
#145

**Comment by bbickerton** [comment]
Waiting for use in #159 tests
