### ISSUE TITLE
Mock Service Provider for systemd

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#167]
## Issue Description

In order to complete adequate testing of #159 Status Pusher, several mock providers must be made.  The scope of this card is to create a mock service provider to interact with systemd.  The real provider is being handled in #166 Service Provider (systemd abstraction).
## Acceptance Criteria (How do we know when this is done?)

Functioning well enough to complete testing on #159.
## Related Tickets
#159
#166

**Comment by bbickerton** [comment]
Bulk of this done. Need to integrate with #159
