### ISSUE TITLE
dnsmasq

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#206]
#### Issue Description

First determine if/how it can be used. It'd be great to punt all the networking to dnsmasq (including tftp'ing ipxe), which calls for dnsmasq asking another binary for the actual ip allocation.

May result in another card or transfer to Nahaum.

**Comment by mmlb** [comment]
dnsmasq has no way to ask for a lease from some-other binary, it will only inform others of a choice made. We would rather it be the other way around so it's not useful to us.
