### ISSUE TITLE
Configure Jenkins to Push Artifacts to S3

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#212]
#### Issue Description

CeranaOS builds are done in a docker container on dev-2. The artifacts need to be made available to others. This is to implement a scheme similar to what was done for Mistify to push the artifacts to known locations on Amazon S3.

**Comment by StevenIsaacs** [comment]
Created a new bucket on S3 and setup Jenkins running on dev-2 to push to the bucket. To download the URL is:
`http://omniti-cerana-artifacts.s3.amazonaws.com/CeranaOS/build-cerana/<build>/artifacts/bzImage`
and
`http://omniti-cerana-artifacts.s3.amazonaws.com/CeranaOS/build-cerana/<build>/artifacts/initrd`

**Comment by StevenIsaacs** [comment]
I added an html file to present the files in a more user friendly manner. The URL is:
http://omniti-cerana-artifacts.s3.amazonaws.com/index.html
