### ISSUE TITLE
Fix statspusher error logging

### ISSUE THREAD

**Issue by bbickerton** [cerana/cerana#232]
#### Issue Description

At least some errors aren't getting logged, just bubbled up, and all that is printed is `encountered an error during startup`. Go through and make sure errors are being logged at some point.
#### Steps to Reproduce (if applicable):

One example: Run with an incomplete config.json (e.g. missing a TTL)
#### Acceptance Criteria (how do we know when this is done?)

All errors are logged

**Comment by mmlb** [comment]
http://dave.cheney.net/2016/06/12/stack-traces-and-the-errors-package is worth looking in to

**Comment by bbickerton** [comment]
I like the wrapping and stack tracing idea a lot.

**Comment by bbickerton** [comment]
Related to #308

**Comment by bbickerton** [comment]
Closing as statspusher has been broken apart in #347 and logging work is being done in #308
