### ISSUE TITLE
Unit File for DHCP Provider

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#250]
#### Issue Description

Need a unit file for DHCP Provider.

**Comment by StevenIsaacs** [comment]
I pushed the `dhcp-provider` unit file to my 237 branch. There's a bug causing `dhcp-provider` to fail with a panic. mm: is looking at it. Also, this looks at the current network configuration to determine the dns server and gateway. There's an odd problem where `route` can't be found during the pre-init script so I worked around that by grabbing the symlink to `route` and used that.

**Comment by StevenIsaacs** [comment]
Nahum provided a variable I can use for an absolute path to the `route` binary.

Now `dhcp-provider` is in panic:

```
Jul 01 17:08:09 5e6facdc-d3d4-495b-bcc7-7b505e83595a dhcp-provider[1079]:         /tmp/nix-build-go1.6-cerana-2016-06-29.drv-0/go/src/github.com/cerana/cerana/cmd/dhcp-provider/main.go:36 +0x211
Jul 01 17:08:09 5e6facdc-d3d4-495b-bcc7-7b505e83595a dhcp-provider[1121]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 01 17:08:09 5e6facdc-d3d4-495b-bcc7-7b505e83595a dhcp-provider[1121]: [signal 0xb code=0x1 addr=0x0 pc=0x5612cd]
Jul 01 17:08:09 5e6facdc-d3d4-495b-bcc7-7b505e83595a dhcp-provider[1121]: goroutine 1 [running]:
```

Manny knows about this and is investigating.

**Comment by StevenIsaacs** [comment]
Moving on. The service starts as part of the layer 2 target but fails due to the panic (above). This task is basically done.
