### ISSUE TITLE
Unit file for service provider

### ISSUE THREAD

**Issue by bbickerton** [cerana/cerana#264]
#### Issue Description

Create a unit file for the `service-provider` command. It uses the basic `provider` configuration.
#### Related Tickets

https://github.com/cerana/cerana/pull/263

**Comment by StevenIsaacs** [comment]
Waiting for merge of the PR for the `service-provider`. (https://github.com/cerana/cerana/pull/263)

**Comment by nshalman** [comment]
Resolved by @StevenIsaacs in https://github.com/cerana/nixpkgs/commit/7af6d99c00b4febd5d6783ca0a776a990a83399e
