### ISSUE TITLE
Add cleanup of old builds on S3.

### ISSUE THREAD

**Issue by StevenIsaacs** [cerana/cerana#270]
#### Issue Description

The builds from Jenkins are accumulating on S3 and will eventually become a problem. Add a mechanism to remove old builds from S3.

**Comment by StevenIsaacs** [comment]
I configured the Jenkins job to use the S3 plugin to manage the build artifacts. This did two things. One, the old builds are now automatically deleted from both Jenkins and S3 and two, the path on S3 changed to include a `jobs` directory (otherwise the same as before). e.g. the path for build 92 becomes:
http://omniti-cerana-artifacts.s3.amazonaws.com/index.html?prefix=CeranaOS/jobs/build-cerana/92/

**Comment by nshalman** [comment]
Can you also update https://github.com/cerana/cerana/blob/master/boot/bin/cerana-update-dev-platform

**Comment by StevenIsaacs** [comment]
Done. Also updated that script to ignore the .md5 extension which is a result of the MD5 signatures being added to the artifacts (#271). See cerana/cerana branch 270_build_cleanup.
