### ISSUE TITLE
Unit file for "bootserver"

### ISSUE THREAD

**Issue by StevenIsaacs** [cerana/cerana#276]
#### Issue Description

Write unit file for the "bootserver" as part of L2 services.

**Comment by nshalman** [comment]
Example config that worked.
the `ipxe` line should contain `${pkgs.ipxe}/undionly.kpxe`
we'll need to find a way to obtain the `dhcp_interface`

``` json
{
  "service_name": "bootserver",
  "socket_dir": "/task-socket/l2-coordinator/",
  "coordinator_url": "unix:///task-socket/l2-coordinator/coordinator/l2-coord.sock",
  "ipxe": "/tmp/undionly.kpxe",
  "kernel": "/data/platform/current/bzImage",
  "initrd": "/data/platform/current/initrd",
  "dhcp-interface": "enp0s3"
}
```

**Comment by StevenIsaacs** [comment]
I created the unit file and pushed to the 276 branch. This may need some tuning once the bootserver merges to master.
