### ISSUE TITLE
unit file for data trade provider

### ISSUE THREAD

**Issue by nshalman** [cerana/cerana#289]
#### Issue Description

Need a unit file for the recently merged data trade provider
#### Acceptance Criteria (how do we know when this is done?)

Data trade provider is running as part of the Layer 2 services on Cerana cluster members
#### Related Tickets
#281
#256

**Comment by StevenIsaacs** [comment]
Created a branch (https://github.com/cerana/nixpkgs/tree/289_data_provider_unit_file) and added the unit file. I verified locally using a VM that the service starts when the `ceranaLayer2.target` is started.
