### ISSUE TITLE
use fmt.Sscanf to discover bundle ids

### ISSUE THREAD

**Issue by mmlb** [cerana/cerana#302]
#### Issue Description

https://github.com/cerana/cerana/blob/master/providers/clusterconf/bundle.go#L235 does a string split and then parses the id string into an int, we can combine finding / parsing the int into just one (arguably clearer) function call with

``` go
var id int
_ = fmt.Sscanf("bundles/42/some/other/stuff", "bundles/%d", &id)
```

see https://play.golang.org/p/97GeYajf-7

**Comment by bbickerton** [comment]
Handled in #309
