### ISSUE TITLE
Split Statspusher in CeranaOS

### ISSUE THREAD

**Issue by bbickerton** [cerana/cerana#347]
#### Issue Description

`statspusher` has been split into three separate commands. The binary called `statspusher` is now gone.

The config for the new services follow the json structure (without the `// Note:` comments). Intervals and timeouts are strings with time units (e.g. "5s") :

```
{
    "nodeDataURL": "",
    "clusterDataURL": "",
    "logLevel": ""
    "requestTimeout": "",
    "tickInterval": "", // Note: formerly {node,bundle,dataset}Interval
    "tickRetryInterval": ""
}
```

Need to:
1. Create service definitions and configs for the following:
   1. `dataset-heartbeat`
      1. Additional required config option `"datasetPrefix":""` (formerly `datasetDir` for `statspusher`)
   2. `bundle-heartbeat`
   3. `node-heartbeat`
2. Remove `statspusher` (config, service definition, binary, etc.) from the CeranaOS build.
#### Acceptance Criteria (how do we know when this is done?)

CeranaOS is happily using the three ticks and not using `statspusher`.
#### Related Tickets
#343

**Comment by StevenIsaacs** [comment]
Added the unit files and pushed. The nixpkgs branch is 347-split-statspusher.
