### ISSUE TITLE
run mistify-os in docker

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#37]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mmlb](https://github.com/mmlb)**
_Mon Feb 29 16:43:39 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/37_

---

**Comment by joshie** [comment]
Closing. Not needed.
