### ISSUE TITLE
Sort out socket permissions

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#46]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Tue Mar  8 19:37:09 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/46_

---

Depending on how the coordinator or provider are run (e.g. with sudo), the created socket and directory may have ownership and permissions that prevent ones run differently (e.g. without sudo) to work and communicate. Decide how to handle and update `coordinator`, `provider`, and `acomm` as needed.

**Comment by joshie** [comment]
@TauZero @nshalman _edited_
My previous comment is probably inaccurate. ideally in the future we could lock down permissions for each provider using daisy, which means they might end up with different users.

However, sockets should we writable by all, and if the socket dir isn't bind mounted, it's pretty protected. It's assumed a malformed request could get to the providers anyway. They each handle how proper the request is or not.

**Comment by joshie** [comment]
we have a newer thread for this topic: https://github.com/cerana/cerana/issues/114 so I am closing this
