### ISSUE TITLE
Polish coordinator/provider/acomm

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#48]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Fri Mar 11 15:56:42 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/48_

---

Review  function signatures and flows after a real provider (e.g. #40 ) has used them. Find anything that doesn't work well or feels clunky and address before making more providers.

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Fri Mar 11 20:53:39 2016_

---

adding `""` for arg in `NewRequest` is particularly wrong looking. Maybe `NewRequest` should just take in the args it needs for validation and returns a default+validated-args Request instead of filling it all in.

**Comment by joshie** [comment]
Closing this because we are probably past this state. Reopen something more focused if needed.
