### ISSUE TITLE
Create CGroup Management Provider

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#53]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Tue Mar 15 21:09:36 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/53_

---

**Comment by bbickerton** [comment]
It can be handled with the unit files created through the service provider with limits defined in the service clusterconf definition. No need for a full provider.
