### ISSUE TITLE
Create Process Management Provider

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#54]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Tue Mar 15 21:10:39 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/54_

---

A generic interface which will, for now, call the systemd provider being created in #52

**Comment by joshie** [comment]
This is, in fact, created. Pinging @TauZero for awareness
