### ISSUE TITLE
Cache Build Dependencies in TravisCI

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#56]
<a href="https://github.com/TauZero"><img src="https://avatars.githubusercontent.com/u/752701?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TauZero](https://github.com/TauZero)**
_Wed Mar 16 19:52:44 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/56_

---

Rebuilding SPL and ZFS every run, for example, is very time consuming. Look into caching with TravisCI https://docs.travis-ci.com/user/caching/ and implement where possible.

**Comment by pjnorton** [comment]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mmlb](https://github.com/mmlb)**
_Wed Mar 16 21:07:36 2016_

---

sgtm, but note that travis based caching is only for pros and containers neither which we meet. So we'd have to setup our own s3 caches.

**Comment by bbickerton** [comment]
One of the biggest problems is spl/zfs

```
spl:
  configure 27s real, 12s user
  make 14s real, 13 user
zfs:
  autogen 13s real, 11 user
  configure 1m20s real, 41s user
  make 2m27s real, 2m17s user
```

If we can archive those, pull them down and install, then `modprobe`, it would save a significant amount of time. The script should be smart enough that if `modprobe` fails, it rebuilds from scratch as a fallback.
