### ISSUE TITLE
iPxe needs to pass the the cluster ips, node ip, and mac address we pxeboot'd from in kernel params

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#68]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Wed Mar 23 21:57:24 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/68_

---
# Issue Description

TBD
# Acceptance Criteria (How do we know when this is done?)

TBD

**Comment by nshalman** [comment]
This stuff has been implemented by @mmlb in the bootserver.
