### ISSUE TITLE
Grub needs to have normal boot (not part of a cluster) and cluster bootstrap option

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#69]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Wed Mar 23 21:57:39 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/69_

---
# Issue Description

Grub should have two boot menu options:

```
MistifyOS
MistifyOS Cluster Bootstrap
```

TBD: Which is the default? Probably normal boot.
# Acceptance Criteria (How do we know when this is done?)

Booting normal boot option boots up MistifyOS in a standalone mode.

Booting Cluster Bootstrap option causes all layer 2 services to be installed so that this machine can act as a DHCP/PXE server for subsequent nodes.

**Comment by joshie** [comment]
Grub has this and more as of today. Closing. pinging @nshalman for awareness
