### ISSUE TITLE
Bootstrap needs to stand up custom consul backed dhcp solution

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#71]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Wed Mar 23 21:58:30 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/71_

---
## Issue Description

TBD
## Acceptance Criteria (How do we know when this is done?)

TBD

**Comment by joshie** [comment]
This is done. Flagging @nshalman for awareness
