### ISSUE TITLE
Move to Cerana

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#80]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Fri Apr  1 14:29:41 2016_
_Originally opened as https://github.com/mistifyio/mistify/issues/80_

---
## Issue Description

Stand up the mistify site on cerana as is with the name change
Point mistify.io to cerana.org instead
Put some stuff in the mistifyio github talking about the move
## Acceptance Criteria (How do we know when this is done?)

mistify site is on cerana and mistify.io points to cerana.org

**Comment by pjnorton** [comment]
<a href="https://github.com/nshalman"><img src="https://avatars.githubusercontent.com/u/20391?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nshalman](https://github.com/nshalman)**
_Fri Apr  1 16:28:07 2016_

---

http://cerana.org/ is now up.
Next is to set up the redirects from mistify.io

**Comment by pjnorton** [comment]
<a href="https://github.com/nshalman"><img src="https://avatars.githubusercontent.com/u/20391?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nshalman](https://github.com/nshalman)**
_Fri Apr  1 17:25:24 2016_

---

http://mistify.io redirects after 3 seconds to http://cerana.org

**Comment by mmlb** [comment]
@nshalman is this closable?

**Comment by joshie** [comment]
Done. Closing
