### ISSUE TITLE
Run Mistify OS SDK in Docker Container under Ubuntu 14.04

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#88]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Tue Mar 22 18:30:05 2016_
_Originally opened as https://github.com/mistifyio/mistify-os/issues/170_

---

SteveIsaacs has had issues attempting to run Mistify OS in a Docker container under Ubuntu 14.04 (3.3 kernel).  The purpose of this task is to analyze the issues encountered and resolve them.

**Comment by StevenIsaacs** [comment]
I wrote as script to simplify the process of properly building a container which can run a build of the MistifyOS SDK. This process has been partially tested on dev-4 and started manually. I'll be using a Jenkins slave connected to the AWS Jenkins master to verify the container can be used to build MistifyOS.

**Comment by nshalman** [comment]
Old Mistify/buildroot ticket. Closing.
