### ISSUE TITLE
add consul implementation of pkg/kv/kv and switch to it

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#93]
<a href="https://github.com/mmlb"><img src="https://avatars.githubusercontent.com/u/708570?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mmlb](https://github.com/mmlb)**
_Tue Mar 22 20:32:20 2016_
_Originally opened as https://github.com/mistifyio/lochness/issues/133_

---
# Description

Bring in pkg/kv from mistifyio/lochness into cerana
# Related Issues
#122 - abstract kv use into a package

**Comment by mmlb** [comment]
Will be brought in along with #123
