### ISSUE TITLE
Convert from etcd to Consul (cerana image service)

### ISSUE THREAD

**Issue by pjnorton** [cerana/cerana#94]
<a href="https://github.com/pjnorton"><img src="https://avatars.githubusercontent.com/u/8000727?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pjnorton](https://github.com/pjnorton)**
_Thu Feb 25 15:55:59 2016_
_Originally opened as https://github.com/mistifyio/mistify-image-service/issues/13_

---

Like with the Lochness service, convert the mistify-image-service from etcd to Consul.

**Comment by joshie** [comment]
Not needed.
